#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/ab25981e-d935-4f2d-8297-61fb98dbb1d8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight motor;
  CloudTemperatureSensor temperature;
  CloudRelativeHumidity humidity;
  CloudRelativeHumidity moisture;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "ESP8266WiFi.h"
#include "thingProperties.h"
#include "DHT.h"

#define DHTPIN D4
#define DHTTYPE DHT11

#define mois A0

DHT dht(DHTPIN, DHTTYPE);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(mois,INPUT);
  pinMode(D1,OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  dht.begin();
}

void loop() {
  // Your code here 
  onMoistureChange();
  onMotorChange();
  onHumidityChange();
  ArduinoCloud.update();
}

/*
  Since Humidity is READ_WRITE variable, onHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange()  {
  // Add your code here to act upon Humidity change
  float h = dht.readHumidity();
  float t = dht.readTemperature();
  humidity = h;
  temperature = t;
  Serial.println("humidity = "); Serial.print(h);
  Serial.println("temperature = "); Serial.print(t);
  Serial.println("");
}


/*
  Since Moisture is READ_WRITE variable, onMoistureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMoistureChange()  {
  // Add your code here to act upon Moisture change
  int m = analogRead(mois);
  m = 145- map(m, 0, 1023, 0, 100);
  moisture = m;
  
  if(moisture<60){
    motor = 1;
   }
  Serial.println("Moisture = "); Serial.print(m); Serial.print("%");
  Serial.println("");
}


/*
  Since Motor is READ_WRITE variable, onMotorChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorChange()  {
  // Add your code here to act upon Motor change
  
  if (moisture<60 && motor == 1){
    digitalWrite(D1,0);
  }
  else{
    digitalWrite(D1,1);
    motor = 0;
  }
}





