// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "dffbe0d1-8479-4f7c-9d8b-104aee3a0335";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMotorChange();
void onHumidityChange();
void onMoistureChange();

CloudLight motor;
CloudTemperatureSensor temperature;
CloudRelativeHumidity humidity;
CloudRelativeHumidity moisture;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(motor, READWRITE, ON_CHANGE, onMotorChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(moisture, READWRITE, ON_CHANGE, onMoistureChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
